import type { NextPage } from "next";

import Head from "next/head";
import { Header } from "../components/header";
import { Menu } from "../components/menu";
import { Product } from "../components/product";

import { mocksData } from "../mocks/sushi";
import { Offers } from "../components/offers";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Menu />
      <Product mocksData={mocksData} title={"Суши"} />
      <Product mocksData={mocksData} title={"Ролы"} />
      <Product mocksData={mocksData} title={"Сеты"} />
      <Offers />
      <Product mocksData={mocksData} title={"Закуски"} />
      <Product mocksData={mocksData} title={"Напитки"} />
    </div>
  );
};

export default Home;
